name: Test

on:
  pull_request:
    branches:
    - main


jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0
        with:
          cluster_name: playground
          config: manifests/kind.yaml

      - name: run
        run: no | ./bootstrap.sh

      - name: bootstrap
        run: |
          cd karchit8cture
          python3 karchit8cture.py