name: Test

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0
          cluster_name: playground
          config: manifests/kind.yaml